version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.build
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
        command: ['./build/test/DrogonApp_test']
