FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update && apt-get install -y \
	g++ \
	cmake \
	make \
	git \
	libjsoncpp-dev \
	uuid-dev \
	openssl \
	libssl-dev \
	zlib1g-dev

RUN git clone https://github.com/drogonframework/drogon.git \
	&& cd drogon \
	&& git submodule update --init \
	&& mkdir build \
	&& cd build \
	&& cmake .. \
	&& make -j $(nproc) && make install

COPY . .